### ISSUE TITLE
Connecting problem

### ISSUE THREAD

**Issue by amanimuhammed** [farhan-dqz/JulieMwol#34]
There is error with your code. I deployed it in morning. It is showing in logs connecting to WhatsApp. I restarted it and even changed the session but it is showing same. Please fix it

[tonystarkub-logs-1630131792116.txt](https://github.com/farhan-dqz/JulieMwol/files/7070557/tonystarkub-logs-1630131792116.txt)

**Comment by farhan-dqz** [comment]
> There is error with your code. I deployed it in morning. It is showing in logs connecting to WhatsApp. I restarted it and even changed the session but it is showing same. Please fix it
> 
> [tonystarkub-logs-1630131792116.txt](https://github.com/farhan-dqz/JulieMwol/files/7070557/tonystarkub-logs-1630131792116.txt)
Hey Bro 😊. This Git has no more updates..
Use 
github.com/farhan-dqz/Julie-Mwol 

and Use that Qr for deploy. 
it Will work 🤗

**Comment by farhan-dqz** [comment]
> There is error with your code. I deployed it in morning. It is showing in logs connecting to WhatsApp. I restarted it and even changed the session but it is showing same. Please fix it
> 
> [tonystarkub-logs-1630131792116.txt](https://github.com/farhan-dqz/JulieMwol/files/7070557/tonystarkub-logs-1630131792116.txt)

https://github.com/farhan-dqz/Julie-Mwol

**Comment by amanimuhammed** [comment]
Tnx bro i will try it 🤩
